commons/fonts: Add _update_fontcache function

diff --git a/catalog/commons/fonts.yaml b/catalog/commons/fonts.yaml
--- a/catalog/commons/fonts.yaml
+++ b/catalog/commons/fonts.yaml
@@ -73,7 +73,24 @@ hooks:
           done
         }
 
+        _update_fontcache() {
+            # unreadable font files = fontconfig segfaults
+            find "${EROOT%/}"/usr/share/fonts/ -type f '!' -perm 0644 \
+                -exec chmod -v 0644 2>/dev/null {} + || die "failed to fix font files perms"
+            if [[ -z ${ROOT%/} ]] ; then
+                # TODO: check if fontconfig is present and is present fc-cache
+                ebegin "Updating global fontcache"
+                fc-cache -fs
+                if ! eend $? ; then
+                    die "failed to update global fontcache"
+                fi
+            else
+                einfo "Skipping fontcache update (ROOT != /)"
+            fi
+        }
+
         setup_all_fonts
+        _update_fontcache
 
 entrypoint:
   - /bin/bash
