eclass_db: Add cleanup_db hook

diff --git a/catalog/eclass/eclass_db.yaml b/catalog/eclass/eclass_db.yaml
--- a/catalog/eclass/eclass_db.yaml
+++ b/catalog/eclass/eclass_db.yaml
@@ -1,4 +1,37 @@
 hooks:
+
+  db_cleanup:
+    remediate: devel_db
+    check: libdb
+    description: |
+      Clean libdb* links and includes.
+    actions:
+      - |-
+        LIB="${EROOT}/usr/lib64"
+
+        source /lib/gentoo/functions.sh
+
+        if [ -z "${SLOT}" ] ; then eerror "Missing SLOT variable" ; exit 1 ; fi
+
+        if [ -e "${LIB}"/libdb.a ] && [ ! -e "${LIB}"/libdb-${SLOT}.a ]; then
+            einfo "Moving libdb.a to a versioned name"
+            mv "${LIB}/libdb.a" "${LIB}/libdb-${SLOT}.a"
+        fi
+
+        if [ -e "${LIB}"/libdb_cxx.a ] && [ ! -e "${LIB}"/libdb_cxx-${SLOT}.a ]; then
+            einfo "Moving libdb_cxx.a to a versioned name"
+            mv "${LIB}/libdb_cxx.a" "${LIB}/libdb_cxx-${SLOT}.a"
+        fi
+
+        find "${LIB}" -maxdepth 1 -type l -name 'libdb[1._-]*so' -exec rm \{} \;
+        find "${LIB}" -maxdepth 1 -type l -name 'libdb[1._-]*so.[23]' -exec rm \{} \;
+        einfo "removing unversioned static archives"
+        find "${LIB}" -maxdepth 1 -type l -name 'libdb[1._-]*a' -exec rm \{} \;
+
+        rm -f \
+            "${ED}"/usr/include/{db,db_185}.h \
+            "${LIB}"/libdb{,_{cxx,sql,stl,java,tcl}}.a
+
   db_fix_so:
     remediate: devel_db
     check: db_includes
